@extends('layouts.app')
@section('stylesheet')

@endsection
@section('content')
    <section class="content">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Generated Pins</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">


                <table class="table table-striped table-bordered table-hover" >
                    <thead>
                    <tr>

                        <td>No of Pins</td>
                        <td>Pins Range</td>
                        <td>Generated By</td>
                        <td>Name of Generator</td>
                        <td>Date Generated</td>

                    </tr>
                    </thead>
                    <tbody>


                    @foreach($pinsgeneratedperday as $pingeneratedperday)
                        <tr>
                                
                            <td>{!!$pingeneratedperday->no_of_pins!!}</td>
                             <td>{!!$pingeneratedperday->minid!!}-{!!$pingeneratedperday->maxid!!}</td>
                            <td>{!!$pingeneratedperday->generated_by!!}</td>
                            <td>{!!$pingeneratedperday->name!!}</td>
                            
                            <td>{!!$pingeneratedperday->date_generated!!}</td>

                        </tr>
                    @endforeach

                    </tbody>

                </table>

            </div>
        </div>
    </section>

@endsection
@section('scripts')



@endsection


